version: "3.7"
services:
  nbs-nginx:
    image: nginx:alpine
    container_name: pulsar_hr_service_nginx
    restart: unless-stopped
    ports:
      - "40001:80"
    volumes:
      - ./:/var/www
      - ./docker/conf/vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nbs_bridge

  nbs-fpm:
    build:
      args:
        user: nbs_user
        uid: 1000
      context: ./
      dockerfile: docker/Fpm.Dockerfile
    image: nbs_biobank_sevice
    container_name: pulsar_hr_sevice_fpm
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - nbs_bridge

networks:
  nbs_bridge:
    external: true
